spring:
  application:
    name: ai-agent
  profiles:
    active: local
  ai:
    ollama: # 调用本地部署大模型的配置
      base-url: http://localhost:11434
      chat:
        model: qwen3:8b
server:
  port: 8124 # 服务端口
  servlet:
    context-path: /api # 接口前缀

# springdoc-openapi knife4j接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cslb.aiagent.controller
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
